/**
 * Custom typings for the "h5p-standalone" npm package
 */
declare module 'h5p-standalone' {
  interface H5POptions {
    /** Path to the H5P content folder */
    h5pJsonPath: string;
    /** URL to the standalone player h5p.css */
    frameCss: string;
    /** URL to the standalone player frame.bundle.js */
    frameJs: string;
    /** Player unique identifier. Randomly generated by default */
    id?: string;
    /** Path where the player should find the H5P content libraries. Defaults to same as h5pJsonPath */
    librariesPath?: string;
    /** Path where the player should find the H5P content.json file. Defaults to {h5pJsonPath}/content/, */
    contentJsonPath?: string;
    /** A boolean on whether to show H5P player frame and buttons */
    frame?: boolean;
    /** A boolean on whether display copyright button */
    copyright?: boolean;
    /** A boolean on whether display a download button. */
    export?: boolean;
    /** A boolean on whether display H5P icon */
    icon?: boolean;
    /** A path or a url that returns zipped h5p for download. The link is used by H5P export button */
    downloadUrl?: string;
    /** A boolean on whether to enable the fullscreen button if the browser supports the feature. Default is false */
    fullScreen?: boolean;
    /** A boolean on whether display embed button. Default is false. N.B. Setting this option to true will require an embedCode below. */
    embed?: boolean;
    /** Embed/Iframe code that user can insert on their site to view the same content. Check some caveats to consider below */
    embedCode?: string;
    /** Path(s) to custom stylesheet file(s) */
    customCss?: string;
    /** Path(s) to custom script file(s) */
    customJs?: string;
    /** An identifier for a single unique Activity ~ utilized when generating xAPI object field. Default is page host+pathname */
    xAPIObjectIRI?: string;

    /** User previous content interaction state data. The data should be in JSON string format */
    contentUserData?: string;
    /** How often current user engagement content state should be autosaved (in seconds). Default is false. */
    saveFreq?: number | false;
    /** Indicates if H5P should post the results once a finish event is triggered. Default is false. Requires ajax.setFinishedUrl property to be set */
    postUserStatistics?: boolean;
    /** Object required if you need H5P to manage a learner's state */
    ajax?: {
      /** Url where H5P should post the results once a finish event is triggered. Requires postUserStatistics to be set to true. */
      setFinishedUrl?: string;
      /** Endpoint where H5P can manage current user state. Requires user property to be set */
      contentUserDataUrl?: string;
    };
    /** Current user data object. */
    user?: {
      /** Used as xAPI actor's name */
      name: string;
      /** User email. Uniquely identifies the xAPI actor */
      mail: string;
    };
  }

  /**
   * The H5P standalone player class
   */
  export class H5P extends Promise<Void> {
    constructor(element: HTMLElement, options: H5POptions);
  }
}
